### ISSUE TITLE
error while installing plugin

### ISSUE THREAD

**Issue by TomSH75** [faiteanu/hibiscus.docmanager#10]
Ich benutze das aktuelle Hibiscus (2.10.20) und habe alle benötigten Plugins gerade installiert. Offenbar gibt es einen Versionskonflikt:
![grafik](https://github.com/faiteanu/hibiscus.docmanager/assets/55321799/c78756fd-ac7d-430f-9485-182ff7a1cd45)

**Comment by faiteanu** [comment]
Es handelt sich um den gleichen Fehler wie bei https://github.com/faiteanu/hibiscus.docmanager/issues/4.
An der entsprechenden Stelle müssen manuell die Dateien h2-create.sql und update0001.sql gelöscht werden, danach funktioniert das Plugin. 

Falls jemand mir sagen kann, wie man den Updater (`de.willuhn.sql.version.Updater`) konfiguriert oder programmiert, so dass das Problem nicht mehr auftritt, gerne her mit den Infos oder direkt einen PR erstellen.

**Comment by schuessm** [comment]
Hello I do so, but I got always the following error
![Bildschirmfoto vom 2024-06-15 11-55-06](https://github.com/faiteanu/hibiscus.docmanager/assets/16079397/0b7f37e1-5d24-43bf-8fa6-4f79afcbe81b)
I use hibiscus 2.10.20. I delete first the content of both files an tried it, then I deleted the whole files. But in same Case the same result

**Comment by faiteanu** [comment]
@schuessm Your screenshot says DocManager Version 0.2.1, while the current version is 0.2.6. Please try updating first.

**Comment by schuessm** [comment]
@faiteanu I did the installation by the description with this link: https://faiteanu.github.io/hibiscus.docmanager. whre did I find 0.2.6?

**Comment by faiteanu** [comment]
In Jameica go to Datei -> Einstellungen -> Plugins -> Updates. That looks similar to the first image in this thread. DocManager 0.2.6 should be displayed in that list. Click Aktualisieren.

**Comment by schuessm** [comment]
Perfekt. Danke. Jetzt funktioniert alles mit dem kleinen Hack der 2 Dateien :-)
