### ISSUE TITLE
TAN Flickercode wird nicht angezeigt

### ISSUE THREAD

**Issue by ghost** [faiteanu/hibiscus.docmanager#2]
Hallo faiteanu,
habe heute deinen DocManager installiert. Als ich dann die Docs von der DKB abholen wollte, sollte ich die generierte TAN eingeben aber der Flickercode-Dialog wurde mir nicht angezeigt. Was mache ich falsch bzw. was mus ich tun?
Ich habe Hibiscus 2.10.3 / HBCI4Java-Version 3.1.55 / Datenbank-Version 68 am Start unter Apple M1 / macOS 11.3.1

**Comment by faiteanu** [comment]
Funktioniert der Abruf von Umsätzen der DKB-Kreditkarte?
DocManager benutzt für den Login bei der DKB die Bibliothek finance.websync, d.h. wenn der Login bei der Kreditkarte funktioniert, müsste er auch beim DocManager genauso laufen.

Soweit ich weiß, unterstützt finance.websync den Flickercode jedoch nicht. Da ich selber kein chipTAN habe, kann ich es allerdings nicht testen.

Vielleicht hilft dieser Link: https://scripting-forum.derrichter.de/viewtopic.php?f=34&t=1098

**Comment by ghost** [comment]
Umsätze der DKB-Kreditkarte können meines Wissens nach nicht direkt abgerufen werden. Die Kreditkarte gibt es nur im Verbund mit einem DKB Girokonto. Diese Konto habe ich in Hibiscus eingepflegt und kann auch die Umsätze abrufen. Etwa alle 3 Monate wird eine Authentifizierung verlangt und dann kommt im Hibiscus auch der Flickercode-Dialog nach vorne. Diese Authentifizierung wird auch von anderen Banken vorgenommen und funktioniert mit Hibiscus tadellos. Falls man doch das Kreditkartenkonto direkt abrufen kann, wüsste ich nicht wie. Siehe auch hier: https://community.comdirect.de/t5/Konto-Depot-Karte/VISA-Ums%C3%A4tze-mit-HBCI-jameica-hibiscus-abrufen/td-p/65033

finance.websync nutze ich in der Version 0.9.23, auch das Rundum-Sorglos-Paket von Hibiscus Mashup hatte ich vor dem DocManager in der neuesten stabilen Version installiert. Hat bei mir aber keinen Einfluss gehabt. Was nun?

**Comment by faiteanu** [comment]
Umsätze der DKB-Kreditkarte können nicht über HBCI abgerufen werden, das ist schon richtig. Dafür gibt es das Hibiscus-Mashup Plugin, welches per Screen-Scraping die Kreditkartenumsätze aus der DKB-Webseite ausliest. DocManager liest die Dokumente auf die gleiche Weise aus der Webseite aus. Der Code für den Webseiten-Login liegt in finance.websync.

Dass der Flickercode beim Abruf des Girokontos über HBCI in Hibiscus funktioniert, ist technisch etwas komplett anderes als das Screen-Scraping über finance.websync. Du könntest versuchen, im entsprechenden Forum zu fragen, ob finance.websync um die Flickercode-Funktionalität erweitert werden kann:
https://scripting-forum.derrichter.de/viewforum.php?f=34

**Comment by ghost** [comment]
Da alles bei mir auf dem neuesten Stand ist, vermute ich, dass das Auslesen über die Webseite das Problem ist. Denn wenn ich mich selbst über den Browser bei der DKB einlogge, muss ich mich neben der Benutzerkennung und dem Passwort eben auch mit einer TAN, durch Flickercode generiert, verifizieren.
Zu deinem Link: Ich habe alle Posts zum Thema DKB gelesen. Eine Bemerkung hat mich stutzig gemacht (es geht um DKB Visa Abruf):
"Bei chipTan-QR kann man und werde ich wie bei photoTan das "Bild" mit dem QR-Code weitergeben, bei Flickercode wird dies so nicht möglich sein und es gibt auch keinen Berechnungscode dafür den man lesen könnte, das läuft am Bank-Server ab ... also wird das mit Flichercode nix werden, mit QR-Code aber kein Problem ..." Ich weiß aber nicht, ob das auch auf finance.websync zutrifft. Darum habe jetzt mal die von dir angeregte Frage ins Forum gestellt. Zur Not muss ich halt auf den DocManager verzichten :(

Vielen Dank für deine Zeit und Mühe!
Grüße, Christberg

**Comment by faiteanu** [comment]
Habe gerade in dem Forum gesucht und bin auf Folgendes gestoßen:
https://scripting-forum.derrichter.de/viewtopic.php?t=770#p4533
Zitat: "Wie oben angeben wird "chipTAN optisch (Flichercode)" aber weiterhin nicht unterstützt! Dies wird so wie es Aussicht auch nicht kommen, also spart euch gleich die Nachfragen."

Damit hat sich das Thema wohl leider erledigt.

Viele Grüße, Fabian

**Comment by dreirund** [comment]
Bei mir geht Abruf von Kreditkarte, aber nicht von Dokumenten, s. #3.

Wenn beide auf das gleiche Backend zurückgreifen sollten, dann scheint es doch kein Problem des Backends zu sein, denn für Kreditkartenumsätze geht es (mit manueller Eingabe des Start-Codes in den TAN-Generator), beim Dokumentenabruf wird mir der Start-Code für die manuelle Eingabe allerdings nicht angezeigt.
