### ISSUE TITLE
Abruf mit USB TAN nicht möglich

### ISSUE THREAD

**Issue by noyannus** [faiteanu/hibiscus.docmanager#6]
Es erscheint derselbe Dialog wie bei #3.

Umstellung auf chipTAN ist wie nach #3 erwartet erfolglos.

Synchronisieren mit Kartenleser funktioniert einwandfrei. 

Ist es überhaupt möglich, nur mit chipTAN oder Kartenleser den docmanager zu nutzen?

**Comment by faiteanu** [comment]
Es handelt sich um das gleiche Problem wie bei #3, daher schließe ich dieses Issue. Ohne Unterstützung durch den Autoren von hibiscus.mashup lässt es sich leider nicht lösen.

**Comment by noyannus** [comment]
Schade, aber wohl nicht zu ändern. 

<strike>Wie löst Ihr das mit Authentifizierung bei docmanager? Ich werde es vorausstl. nicht so hochfrequent nutzen, da kann man schonmal einen Umweg nehmen. </strike>

Hab's rausgefunden: Unter Bank-Zugang die DKB wählen, `TAN-Verfahren zurücksetzen` und auf `chipTAN optisch` setzen. Mglw. vor dem Abrufen der Kontoauszüge einmal das Konto selbst synchronisieren.

EDIT: Einmal hat's geklappt, jetzt geht kein TAN mehr.

Wie kommt Ihr da rein? Oder ist docmanager gestorben..?

**Comment by faiteanu** [comment]
Interessant, dann wird das TAN-Verfahren der DKB von mashup bereitgestellt. Im DocManager ist nichts zum Thema TAN implementiert. Bei der Deka Bank und Baader Bank unterstützt DocManager nur Benutzer+Passwort.
