### ISSUE TITLE
ChromeDriver nach Abbruch nicht löschen

### ISSUE THREAD

**Issue by noyannus** [faiteanu/hibiscus.docmanager#7]
Wenn wegen nicht passender Version der ChromeDriver neu heruntergeladen werden muss -- kann man das so einrichten dass er bei einem Abbruch der Synchronisierung erhalten bleibt? Und erst entsorgt wird, wenn sich die Version ändert?

(Es ist beim Testen unglaublich nervig, jedes mal warten zu müssen bis die immer gleiche Datei beschafft wird.)

**Comment by faiteanu** [comment]
Der ChromeDriver wird vom Plugin hibiscus.scripting.chromedriver verwaltet. Bitte wende dich an dessen Autor über https://scripting-forum.derrichter.de/

**Comment by noyannus** [comment]
OK. Danke!
