### ISSUE TITLE
Logout Deka schlägt fehl

### ISSUE THREAD

**Issue by tlei** [faiteanu/hibiscus.docmanager#8]
Hallo Fabian,

folgende Meldung ist heute beim Logout bei der Deka nach dem erfolgreichen Dokumentenabruf gekommen:

`[Sat Jan 13 13:10:49 CET 2024][ERROR][bg-task:SynchronizeDocuments][name.aiteanu.docmanager.institute.deka.WebSyncDeka.synchronizeDocuments] Logout fehlerhaft; Bitte dem Entwickler im Forum melden!Seite nach Logout-Aufruf unbekannt; Bitte dem Entwickler im Forum melden!`

Installiert: DocManager 0.2.4

Viele Grüße
Thomas

**Comment by faiteanu** [comment]
Hallo Thomas,
danke für den Hinweis. Die Deka hatte das Layout der Webseite minimal geändert.
Mit dem Update auf DocManager 0.2.5 verschwindet die Fehlermeldung.
Viele Grüße,
Fabian
